[supervisord]
nodaemon=true
environment=PYTHONPATH="/walle-service/walle-api-server/"

[program:postgre]
command=/etc/init.d/postgresql restart

[program:walle]
command=/usr/local/bin/gunicorn -w 4 -b 0.0.0.0:8001 walle_api_server.cli.app:app --log-level=error --error-logfile=/var/log/gunicorn_walle.log --reload